CI: Use GNU tar on macOS to work around actions/cache#403 (#350)
We're having more spurious CI failures caused by

error[E0463]: can't find crate for `num_derive`
 --> crates/generated/src/block.rs:3:5
  |
3 |     num_derive::FromPrimitive,
  |     ^^^^^^^^^^ can't find crate

error: aborting due to previous error
Taken from rust-analyzer's CI configuration.

Also changes the cache key so old corrupted caches are no longer used.